import { FaseRoadmap } from "./types"

export const ROADMAP_JAVASCRIPT: FaseRoadmap[] = [
  {
    fase: 1,
    titulo: "Fundamentos",
    duracao: "2 semanas",
    topicos: [
      "O que é JavaScript",
      "Variáveis (let, const, var)",
      "Tipos primitivos",
      "Strings",
      "Numbers",
      "Boolean",
      "Null e Undefined",
    ],
    projeto: "Calculadora simples",
  },
  {
    fase: 2,
    titulo: "Operadores",
    duracao: "1 semana",
    topicos: [
      "Aritméticos (+, -, *, /, %)",
      "Comparação (==, ===, !=, !==)",
      "Lógicos (&&, ||, !)",
      "Ternário",
      "Atribuição",
    ],
    projeto: "Calculadora IMC",
  },
  {
    fase: 3,
    titulo: "Estruturas de Decisão",
    duracao: "1 semana",
    topicos: ["if / else", "else if", "switch", "Operador ternário"],
    projeto: "Sistema de notas",
  },
  {
    fase: 4,
    titulo: "Loops",
    duracao: "1 semana",
    topicos: ["for", "while", "do while", "for...of", "for...in"],
    projeto: "Jogo de adivinhação",
  },
  {
    fase: 5,
    titulo: "Funções",
    duracao: "2 semanas",
    topicos: [
      "function declaration",
      "Arrow functions",
      "Parâmetros",
      "Retorno",
      "Escopo",
      "Closures",
    ],
    projeto: "Gerador de senha",
  },
  {
    fase: 6,
    titulo: "Arrays",
    duracao: "2 semanas",
    topicos: [
      "push / pop",
      "shift / unshift",
      "map",
      "filter",
      "reduce",
      "find / some / every",
    ],
    projeto: "Lista de tarefas",
  },
  {
    fase: 7,
    titulo: "Objetos",
    duracao: "1 semana",
    topicos: [
      "Propriedades",
      "Métodos",
      "Destructuring",
      "Spread operator",
      "JSON",
    ],
    projeto: "Cadastro de clientes",
  },
  {
    fase: 8,
    titulo: "DOM",
    duracao: "2 semanas",
    topicos: [
      "querySelector",
      "addEventListener",
      "createElement",
      "Manipulação de elementos",
      "Classes CSS",
    ],
    projeto: "Todo App visual",
  },
  {
    fase: 9,
    titulo: "Eventos",
    duracao: "1 semana",
    topicos: [
      "click",
      "submit",
      "keyboard",
      "Event delegation",
      "Prevent default",
    ],
    projeto: "Sistema de formulário",
  },
  {
    fase: 10,
    titulo: "Web Storage",
    duracao: "1 semana",
    topicos: ["localStorage", "sessionStorage", "CRUD com storage"],
    projeto: "Notas persistentes",
  },
  {
    fase: 11,
    titulo: "APIs",
    duracao: "2 semanas",
    topicos: ["fetch", "async / await", "Tratamento de erros", "Headers"],
    projeto: "Consulta CEP",
  },
  {
    fase: 12,
    titulo: "Programação Assíncrona",
    duracao: "2 semanas",
    topicos: [
      "Promises",
      "Callbacks",
      "Async/Await",
      "Promise.all",
      "Tratamento de erros",
    ],
    projeto: "Dashboard de clima",
  },
  {
    fase: 13,
    titulo: "ES6+",
    duracao: "2 semanas",
    topicos: [
      "Spread / Rest",
      "Módulos (import/export)",
      "Destructuring",
      "Optional chaining",
      "Nullish coalescing",
    ],
    projeto: "Mini Framework",
  },
  {
    fase: 14,
    titulo: "Orientação a Objetos",
    duracao: "2 semanas",
    topicos: [
      "Classes",
      "Herança",
      "Encapsulamento",
      "Polimorfismo",
      "Getters / Setters",
    ],
    projeto: "Sistema bancário",
  },
  {
    fase: 15,
    titulo: "JavaScript Profissional",
    duracao: "3 semanas",
    topicos: [
      "Design Patterns",
      "SOLID",
      "Clean Code",
      "Arquitetura",
      "Testes",
    ],
    projeto: "ERP completo",
  },
]

export const ROADMAP_SAAS: FaseRoadmap[] = [
  {
    fase: 1,
    titulo: "Fundamentos",
    duracao: "2 semanas",
    topicos: [
      "Variáveis, tipos, funções",
      "Arrays e objetos",
      "DOM e Eventos",
      "localStorage",
    ],
    projeto: "Base do app de estudos",
  },
  {
    fase: 2,
    titulo: "DOM Avançado",
    duracao: "1 semana",
    topicos: [
      "Manipulação avançada do DOM",
      "Event delegation",
      "Renderização dinâmica",
    ],
    projeto: "Interface do app de estudos",
  },
  {
    fase: 3,
    titulo: "APIs com fetch",
    duracao: "2 semanas",
    topicos: ["fetch", "async/await", "CRUD", "Tratamento de erros"],
    projeto: "Conectar app a uma API",
  },
  {
    fase: 4,
    titulo: "Firebase",
    duracao: "2 semanas",
    topicos: [
      "Firestore",
      "Auth",
      "Regras de segurança",
      "Integração com Next.js",
    ],
    projeto: "Autenticação no app de estudos",
  },
  {
    fase: 5,
    titulo: "Supabase",
    duracao: "2 semanas",
    topicos: [
      "Supabase client",
      "Realtime",
      "Row Level Security",
      "Storage",
    ],
    projeto: "Backend do app com Supabase",
  },
  {
    fase: 6,
    titulo: "Node.js + Express",
    duracao: "2 semanas",
    topicos: [
      "Rotas",
      "Middleware",
      "REST API",
      "Banco de dados",
      "Autenticação JWT",
    ],
    projeto: "API própria para o app",
  },
  {
    fase: 7,
    titulo: "Next.js Fullstack",
    duracao: "3 semanas",
    topicos: [
      "Server Components",
      "Server Actions",
      "API Routes",
      "Autenticação",
      "Cache",
    ],
    projeto: "Versão completa do app em Next.js",
  },
  {
    fase: 8,
    titulo: "Autenticação e Multi-Tenant",
    duracao: "2 semanas",
    topicos: [
      "NextAuth / Auth.js",
      "RBAC",
      "Multi-tenant",
      "Segurança",
    ],
    projeto: "Sistema de login e planos",
  },
  {
    fase: 9,
    titulo: "IA com Gemini",
    duracao: "2 semanas",
    topicos: [
      "API Gemini",
      "Prompts",
      "Streaming",
      "Embeddings",
    ],
    projeto: "Assistente IA no app",
  },
  {
    fase: 10,
    titulo: "ERP Real",
    duracao: "4 semanas",
    topicos: [
      "Arquitetura ERP",
      "Módulos",
      "Relatórios",
      "Dashboard",
      "Deploy",
    ],
    projeto: "Módulo ERP dentro do app",
  },
]
